<a href="https://colab.research.google.com/github/soda1102/AI_26/blob/main/numpy_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
print(np.array([1,2,3]))

[1 2 3]


In [3]:
import numpy
print(numpy.array([1,2,3]))

[1 2 3]


In [4]:
import numpy as np

arr_1 = np.array([1,2,3,4,5])
print(arr_1)

[1 2 3 4 5]


In [5]:
[1,2,3,4,5]*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [6]:
arr_1*2

array([ 2,  4,  6,  8, 10])

In [7]:
import numpy as np

arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
import numpy as np
arr_3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(arr_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [10]:
import numpy as np

arr_1 = np.array([1,2,3,4,5])
print(arr_1.dtype)
# 부호가 있는 64비트 정수를 뜻함

int64


In [11]:
import numpy as np
print(np.array([1,2,3]).dtype)

int64


In [12]:
print(np.array([1,2,3], dtype='int8').dtype)

int8


In [13]:
print(np.array([1,2,3], dtype='i1').dtype)

int8


In [14]:
import numpy as np

ndarray_1 = np.array([1,2,3])  # 넘파이 배열
ndarray_2 = np.array([4,5,6])  # 넘파이 배열

list_1 = [1,2,3]  # 파이썬리스트
list_2 = [4,5,6]  # 파이썬리스트

In [15]:
print(ndarray_1 + ndarray_2)
print(list_1 + list_2)

[5 7 9]
[1, 2, 3, 4, 5, 6]


In [16]:
result_list = [x + y for x, y in zip(list_1, list_2)]
print(result_list)

[5, 7, 9]


In [17]:
print(ndarray_1 * 2)
print(list_1 * 2)

[2 4 6]
[1, 2, 3, 1, 2, 3]


In [18]:
import numpy as np

a = np.array([2,3,4])  # 넘파이 정수형 배열 생성
print(a)  # 넘파이 배열 출력
print(a.dtype)  # 넘파이 배열의 데이터 타입 출력
b = np.array([2.1,3.2,4.3])  # 넘파이 실수형 배열 생성
print(b)  # 넘파이 배열 출력
print(b.dtype)  # 넘파이 배열의 데이터 타입 출력

[2 3 4]
int64
[2.1 3.2 4.3]
float64


In [19]:
c = np.array(('i','j','k'))  # 넘파이 문자열 배열 생성
print(c)
print(c.dtype)  # 데이터 타입 확인

['i' 'j' 'k']
<U1


In [20]:
d = np.array((True, True, False))  # 넘파이 논리형 배열 생성
print(d)
print(d.dtype)

[ True  True False]
bool


In [22]:
e = np.array(['ab', 'cd', 'e'], dtype='<U2')  # 문자열 길이를 조절하여 배열 생성
print(e)
print(e.dtype)

['ab' 'cd' 'e']
<U2


In [23]:
import numpy as np

# a라는 변수에 (3,4) 크기의 넘파이 2차원 배열 생성

a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)

(3, 4)
2
int64
8
12


In [26]:
import numpy as np

# 각 학급에 4명의 학생, 각 학생이 3과목의 시험 점수를 가지고 있는 배열 생성
# 예시 : 3개의 학급, 각 학급에 4명의 학생, 각 학생당 국어, 영어, 수학 점수
scores = np.random.randint(0, 101, size=(3,4,3))

# 학급별, 학생별, 과목별 점수를 출력
print("학급별 학생들의 점수 배열 (3차원 배열) : ")
print(scores)

#학급, 학생, 과목별로 점수 출력
for class_idx in range(scores.shape[0]):
  print(f"\nClass {class_idx + 1}")
  for student_idx in range(scores.shape[1]):
    korean, english, math = scores[class_idx, student_idx]
    print(f"Student {student_idx + 1} - Korean : {korean}, English : {english}, Math : {math}")

학급별 학생들의 점수 배열 (3차원 배열) : 
[[[ 65  54  84]
  [ 74  53  53]
  [  6  13  76]
  [ 55  85  42]]

 [[ 72  75  41]
  [ 38  14  25]
  [  3   9  55]
  [ 45  58  38]]

 [[ 72  69  40]
  [ 58  92  35]
  [  1  89  38]
  [ 32  65 100]]]

Class 1
Student 1 - Korean : 65, English : 54, Math : 84
Student 2 - Korean : 74, English : 53, Math : 53
Student 3 - Korean : 6, English : 13, Math : 76
Student 4 - Korean : 55, English : 85, Math : 42

Class 2
Student 1 - Korean : 72, English : 75, Math : 41
Student 2 - Korean : 38, English : 14, Math : 25
Student 3 - Korean : 3, English : 9, Math : 55
Student 4 - Korean : 45, English : 58, Math : 38

Class 3
Student 1 - Korean : 72, English : 69, Math : 40
Student 2 - Korean : 58, English : 92, Math : 35
Student 3 - Korean : 1, English : 89, Math : 38
Student 4 - Korean : 32, English : 65, Math : 100


In [30]:
import numpy as np
print(np.zeros((3, 4)))
print(np.zeros((3, 4), dtype=int))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [31]:
# (2, 3, 4) 크기의 배열을 생성하여 데이터 타입을 정수로 설정한 후 1로 채움

print(np.ones((2, 3, 4), dtype=int))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [32]:
print(np.empty((2, 3)))

[[6.14773442e-316 0.00000000e+000 6.88490756e-310]
 [6.88490731e-310 6.88490731e-310 5.29940345e-317]]


In [33]:
import numpy as np

# 10이상 30 미만 까지 5 간격으로 생성
print(np.arange(10, 30, 5))

# 0이상 2 미만 까지 0.3 간격으로 생성
print(np.arange(start = 0, stop = 2, step = 0.3))

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [34]:
# 1이상 10 이하까지 값을 가진 크기 10짜리 배열 생성
print(np.linspace(start = 1, stop = 10, num = 10, dtype = int))

[ 1  2  3  4  5  6  7  8  9 10]


In [35]:
import numpy as np

# a와 b 배열 생성하여 출력
a = np.array([10, 20, 30, 40])
b = np.arange(start =1, stop = 5)
print(a)
print(b)

# 덧셈연산
print(a + b)

# 뺄셈연산
print(a - b)

# 곱셈연산
print(a * b)

# 나눗셈연산
print(a / b)

[10 20 30 40]
[1 2 3 4]
[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [36]:
# A와 B 배열 생성
A = np.array([[1, 1], [0, 1]])

B = np.array([[2, 0], [3, 4]])

# A * B : 요소별 곱셈 연산
print(A * B)

# A @ B : 행렬 곱셈 사용
print(A @ B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [38]:
import numpy as np

# A와 B 배열 생성
A = np.array([1, 2, 3, 4])
B = np.array([1, 1, 3, 3])

# 비교연산
print(A > B)
print(A == B)

[False  True False  True]
[ True False  True False]


In [40]:
import numpy as np

# 두 학생의 시험 점수를 배열로 생성 (국어, 영어, 수학)
student1_scores = np.array([85, 90, 78])
student2_scores = np.array([92, 88, 95])

# 두 학생의 점수 출력
print("학생1의 점수 : ", student1_scores)
print("학생2의 점수 : ", student2_scores)

# 두 학생의 총점 출력
total_scores = student1_scores + student2_scores
print("두 학생의 총점 : ", total_scores)

# 두 학생의 평균 출력
student1_total = np.sum(student1_scores)
student2_total = np.sum(student2_scores)
student1_average = np.mean(student1_scores)
student2_average = np.mean(student2_scores)

print("학생1의 총점 : ", student1_total)
print("학생1의 평균 : ", student1_average)
print("학생2의 총점 : ", student2_total)
print("학생2의 평균 : ", student2_average)

학생1의 점수 :  [85 90 78]
학생2의 점수 :  [92 88 95]
두 학생의 총점 :  [177 178 173]
학생1의 총점 :  253
학생1의 평균 :  84.33333333333333
학생2의 총점 :  275
학생2의 평균 :  91.66666666666667


In [41]:
import numpy as np

# A 배열 생성
A = np.array([4, 16, 25])

# 제곱근 함수
print(np.sqrt(A))

[2. 4. 5.]


In [42]:
# a 배열 생성 & 출력
# 0부터 8미만까지 출력하고 (2,4) 크기로 재가공하고 제곱하여 출력

a = np.arange(8).reshape(2,4) ** 2
print(a)

# 모든 요소의 합
print(a.sum())

# 모든 요소 중 평균
print(a.mean())

# 모든 요소 중 최솟값
print(a.min())

# 모든 요소 중 최댓값
print(a.max())

# 모든 요소의 누적합
print(a.cumsum())

# 모든 요소 중 최댓값의 인덱스
print(a.argmax())

[[ 0  1  4  9]
 [16 25 36 49]]
140
17.5
0
49
[  0   1   5  14  30  55  91 140]
7


In [43]:
import numpy as np

# 0부터 8미만까지 출력하고 (2,4) 크기로 재가공하고 제곱하여 출력
# a = array([[0 , 1, 4, 9], [16, 25, 36, 49]])

a = np.arange(8).reshape(2,4) ** 2

# axis = 0은 열 기준으로 연산
print(a.mean(axis = 0))
# axis = 1은 행 기준으로 연산
print(a.max(axis = 1))

[ 8. 13. 20. 29.]
[ 9 49]


In [45]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5])
print(a)

# 인덱스가 0인, 인덱스가 3인 요소 출력
print(a[0])
print(a[3])

[0 1 2 3 4 5]
0
3


In [46]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)

# 인덱스가 [1, 0]인, 인덱스가 [1, 2]인 요소 출력
print(b[1, 0])
print(b[1, 2])

[[0 1 2]
 [3 4 5]]
3
5


In [48]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5])
print(a)

# 인덱스 0 이상 인덱스 3 미만 범위의 요소 출력
print(a[0:3])

[0 1 2 3 4 5]
[0 1 2]


In [49]:
import numpy as np

a = np.arange(12).reshape(3,4)
print(a)

# a>4 조건을 적용한 논리형 배열 생성
b = a > 4
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [50]:
print(a[b])  # 논리형 배열 b를 사용하여 조건에 맞는 요소를 추출
print(a[b].shape)  # 추출한 요소들의 배열 모양

[ 5  6  7  8  9 10 11]
(7,)


In [51]:
# 논리형 배열인 b를 이용하여 원본  a 배열의 값 변경하기(True인 값의 위치에 변경하기)
a[b] = 1000
print(a)

[[   0    1    2    3]
 [   4 1000 1000 1000]
 [1000 1000 1000 1000]]


In [52]:
import numpy as np

a = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
i = np.array([1, 1, 3, 4])

# 배열 a에서 배열 i에 지정된 인덱스의 원소들을 출력
print(a[i])
j = np.array([[3, 4], [5, 6]])

# 배열 a에서 배열 j에 지정된 인덱스의 원소들을 출력
print(a[j])

['b' 'b' 'd' 'e']
[['d' 'e']
 ['f' 'g']]


In [53]:
b = np.array(['a', 'b', 'c', 'd'])
k = np.array([3, 2, 1, 0])

# 배열 b에서 배열 k에 지정된 인덱스의 원소들을 재배열
b = b[k]
print(b)

['d' 'c' 'b' 'a']


In [54]:
import numpy as np

# a 배열 생성
a = np.arange(12).reshape(3, 4)
print(a)
print(a.shape)
print(a.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [55]:
# .reshape : 지정한 차원으로 변경하고 새로운 배열 반환
b = a.reshape(2, 6)
print(b)
print(b.shape)

 #원본 a 배열은 기존의 (3, 4) 형태 유지
print(a)
print(a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [56]:
# 1번째 매개변수에 -1을 전달해도 같은 결과가 나옴(자동계산)
c = a.reshape(-1, 3)

In [58]:
import numpy as np

# .resize() : 지정한 차원으로 변경하고 원본 배열 자체를 변경
a = np.arange(12)
a.resize(4, 3)
print(a)
print(a.shape)

# 따로 반환하는 값 없음
print(a.resize(4, 3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
None


In [60]:
import numpy as np

a = np.arange(12).reshape(3, 4)

# .ravel() : 1차원 배열로 크기 변경
print(a.ravel())

# .reshape(-1) : 1차원 배열로 크기 변경
print(a.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [62]:
import numpy as np

A = np.arange(12).reshape(2, 6)
print(A)

# .T : [2, 6]을 [6, 2] 반환으로 전치(transpose) 변환
print(A.T)
print(A.T.shape)

# 만약 전치 형태로 원본 A 배열에 저장하고 싶다면, A배열에 A.T 값을 할당
A = A.T
print(A)
print(A.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)


In [63]:
import numpy as np

# a 배열, b 배열 생성
a = np.array([1, 2, 3, 4]).reshape(2, 2)
b = np.array([5, 6, 7, 8]).reshape(2, 2)

# 수직으로 합치기
print(np.vstack((a, b)))

# 수평으로 합치기
print(np.hstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [64]:
import numpy as np

# a 배열, b 배열 생성
a = np.arange(12).reshape(2, 6)
print(a)

# 수직으로 분할하기
print(np.vsplit(a, 2))

# 수평으로 분할하기
print(np.hsplit(a, 3))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]
